// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4bb7Sinrjwp8Yy4Tf0JqIgRMx6KC0pcI',
    appId: '1:812856292209:web:55c284d8819dda7896fcd0',
    messagingSenderId: '812856292209',
    projectId: 'mechmattut-d66a9',
    authDomain: 'mechmattut-d66a9.firebaseapp.com',
    storageBucket: 'mechmattut-d66a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKaprA6tep9r-vyQqNIfx54XWjwjs4QJw',
    appId: '1:812856292209:android:1d898a1a69853e2b96fcd0',
    messagingSenderId: '812856292209',
    projectId: 'mechmattut-d66a9',
    storageBucket: 'mechmattut-d66a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGqPjWlBR1B10b_s1q5nTHMWrWjPkhQcY',
    appId: '1:812856292209:ios:a38130343910290496fcd0',
    messagingSenderId: '812856292209',
    projectId: 'mechmattut-d66a9',
    storageBucket: 'mechmattut-d66a9.appspot.com',
    iosClientId: '812856292209-3kt75f1q9tfcvm5tofvkbk9b8q62rgci.apps.googleusercontent.com',
    iosBundleId: 'ompus.mechmatTut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGqPjWlBR1B10b_s1q5nTHMWrWjPkhQcY',
    appId: '1:812856292209:ios:a38130343910290496fcd0',
    messagingSenderId: '812856292209',
    projectId: 'mechmattut-d66a9',
    storageBucket: 'mechmattut-d66a9.appspot.com',
    iosClientId: '812856292209-3kt75f1q9tfcvm5tofvkbk9b8q62rgci.apps.googleusercontent.com',
    iosBundleId: 'ompus.mechmatTut',
  );
}
